### Bioinformatics- Species###
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(vegan)
library(tidyverse)
library(ggforce)

Bioinfo_Species<-read_excel("/Users/Thomas/Desktop/Nemabiome/nemabiome_new/Nemabiome-refined.xlsx", sheet="Bioinformatics_Species_new")
str(Bioinfo_Species)
head(Bioinfo_Species)

Bioinfo_Species$Pooling<-as.factor(Bioinfo_Species$Pooling)
Bioinfo_Species$Cow<-as.factor(Bioinfo_Species$Cow)
Bioinfo_Species$Replicates<-as.factor(Bioinfo_Species$Replicates)
Bioinfo_Species$Primer<-as.factor(Bioinfo_Species$Primer)

 
#make community matrix - extract columns with abundance information, the 5 indicates that you cull everything before column 5 as those treatments arent appropriate for out thing
com = Bioinfo_Species[,5:ncol(Bioinfo_Species)]
head(com)

df_com<-as.data.frame(com)
# removed the zero data rows(in excel)
BC<-vegdist(df_com, method="bray")

adonis(BC ~ Replicates+ Primer + Pooling, Bioinfo_Species, perm=200)

#turn abundance data frame into a matrix
m_com = as.matrix(com)
head(m_com)

# now we create our NMDS (set seed makes sure we get the same result every time):
set.seed(123)
nmds = metaMDS(m_com, distance = "bray")
nmds
# for a good representation on our data we are after a stress level of less than 0.2, if its zero then you might have an outlier thats very different to the other samples. 

plot(nmds)

# to plot it in ggplots2 we need to extract the NMDS coordinates for NMDS1 and NMDS2 axes, then put them into a new dataframe called "data.scores"
#extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds)$ sites)

#add columns to data frame 
data.scores$Cow = Bioinfo_Species$Cow
data.scores$Primer = Bioinfo_Species$Primer
data.scores$Pooling = Bioinfo_Species$Pooling
data.scores$Replicates=Bioinfo_Species$Replicates

data.scores$Primer<-as.factor(data.scores$Primer)
data.scores$Cow<-as.factor(data.scores$Cow)
data.scores$Pooling<-as.factor(data.scores$Pooling)
data.scores$Replicates<-as.factor(data.scores$Replicates)

data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "one_replicate"="No pooling"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "two_replicates"="Pooling of 2 replicates"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "three_replicates"="Pooling of 3 replicates"))
count(data.scores, Pooling)

head(data.scores)

env= Bioinfo_Species[,4]

head(env)

env$Cow<-as.factor(env$Cow)

en = envfit(nmds, env, permutations = 999)

en

en_coord_cat = as.data.frame(scores(en, "factors"))
en_coord_cat 

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes(shape = Primer, colour = Pooling))+ geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
       data = en_coord_cat, size =1, alpha = 0.5, colour = "grey30")  + geom_text(data = en_coord_cat, aes(x = NMDS1, y = NMDS2), colour = "grey30", 
       fontface = "bold", label= row.names(en_coord_cat))+ 
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "Pooling", y = "NMDS2", shape = "Primer")  
 
xx

env= Bioinfo_Species[,1]

head(env)

env$Pooling<-as.factor(env$Pooling)

en = envfit(nmds, env, permutations = 999)

en

en_coord_cat = as.data.frame(scores(en, "factors"))
en_coord_cat 

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes( colour = Replicates))+ geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
       data = en_coord_cat, size =1, alpha = 0.5, colour = "grey30")  + geom_text(data = en_coord_cat, aes(x = NMDS1, y = NMDS2), colour = "grey30", 
       fontface = "bold", label= c("one replicate", "three replicates", "two replicates")) +
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "PCR replicates", y = "NMDS2")  
 
xx

### Bioinformatics- ASVs###
Bioinfo_Species<-read_excel("/Users/Thomas/Desktop/Nemabiome/nemabiome_new/Nemabiome-refined.xlsx", sheet="Bioinformatics_ASVs_new")
str(Bioinfo_Species)
head(Bioinfo_Species)

Bioinfo_Species$Pooling<-as.factor(Bioinfo_Species$Pooling)
Bioinfo_Species$Cow<-as.factor(Bioinfo_Species$Cow)
Bioinfo_Species$Replicates<-as.factor(Bioinfo_Species$Replicates)
Bioinfo_Species$Primer<-as.factor(Bioinfo_Species$Primer)

#had issues in the data with empty values, used this code to handle it otherwise couldn't run a NMDS or PERMANOVA
Bioinfo_Species<-na.omit(Bioinfo_Species)

Bioinfo_Species[is.na(Bioinfo_Species)] <- 0

#make community matrix - extract columns with abundance information, the 5 indicates that you cull everything before column 5 as those treatments arent appropriate for out thing
com = Bioinfo_Species[,5:ncol(Bioinfo_Species)]
head(com)

df_com<-as.data.frame(com)
# removed the 0 data rows and columns but still having issues so using this code
BC<-vegdist(df_com, method="bray", na.rm=TRUE)

adonis(BC ~ Replicates+ Primer + Pooling, Bioinfo_Species, perm=200, na.rm=TRUE)

#turn abundance data frame into a matrix
m_com = as.matrix(com)
head(m_com)

# this is to remove data with no values
m_com <- na.omit(m_com)

# now we create our NMDS (set seed makes sure we get the same result every time):
set.seed(123)
nmds = metaMDS(m_com, distance = "bray")
nmds
# for a good representation on our data we are after a stress level of less than 0.2, if its zero then you might have an outlier thats very different to the other samples

plot(nmds)

# to plot it in ggplots2 we need to extract the NMDS coordinates for NMDS1 and NMDS2 axes, then put them into a new dataframe called "data.scores"
#extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds)$ sites)

#add columns to data frame 
data.scores$Primer = Bioinfo_Species$Primer
data.scores$Pooling = Bioinfo_Species$Pooling
data.scores$Replicates = Bioinfo_Species$Replicates

data.scores$Primer<-as.factor(data.scores$Primer)
data.scores$Pooling<-as.factor(data.scores$Pooling)
data.scores$Replicates<-as.factor(data.scores$Replicates)

data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "one_replicate"="No pooling"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "two_replicates"="Pooling of 2 replicates"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "three_replicates"="Pooling of 3 replicates"))
count(data.scores, Pooling)

head(data.scores)

env= Bioinfo_Species[,2]

head(env)

env$Cow<-as.factor(env$Cow)

en = envfit(nmds, env, permutations = 999)

en

en_coord_cat = as.data.frame(scores(en, "factors"))
en_coord_cat 

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes( shape = Primer, colour = Pooling))+ geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
       data = en_coord_cat, size =1, alpha = 0.5, colour = "grey30")  + geom_text(data = en_coord_cat, aes(x = NMDS1, y = NMDS2), colour = "grey30", 
       fontface = "bold", label= row.names(en_coord_cat))+
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "Pooling", y = "NMDS2", shape = "Primer")  
 
xx

#replicates
xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes(colour = Replicates))+ 
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "Replicates", y = "NMDS2")  
 
xx

