### Sequencing depth- Species###
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(vegan)
library(tidyverse)
library(ggforce)

Depth_Species<-read_excel("/Users/Thomas/Desktop/Nemabiome/nemabiome_new/Nemabiome-refined.xlsx", sheet="Depth_Species_new")
str(Depth_Species)
head(Depth_Species)

Depth_Species$Pooling<-as.factor(Depth_Species$Pooling)
Depth_Species$Cow<-as.factor(Depth_Species$Cow)
Depth_Species$Depth<-as.factor(Depth_Species$Depth)

#make community matrix - extract columns with abundance information, the 5 indicates that you cull everything before column 5 as those treatments arent appropriate for PERMANOVA
com = Depth_Species[,5:ncol(Depth_Species)]
head(com)

df_com<-as.data.frame(com)

BC<-vegdist(df_com, method="bray")

Depth_Species_Primer<-adonis(BC ~ Depth + Primer + Pooling, Depth_Species, perm=200)

Depth_Species_Primer

#turn abundance data frame into a matrix
m_com = as.matrix(com)
head(m_com)

# now we create our NMDS (set seed makes sure we get the same result every time):
set.seed(123)
nmds = metaMDS(m_com, distance = "bray")
nmds
# for a good representation on our data we are after a stress level of less than 0.2, if its zero then you might have an outlier thats very different to the other samples. 

plot(nmds)

# to plot it in ggplots2 we need to extract the NMDS coordinates for NMDS1 and NMDS2 axes, then put them into a new dataframe called "data.scores"
#extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds)$ sites)

#add columns to data frame 
data.scores$Cow = Depth_Species$Cow
data.scores$Primer = Depth_Species$Primer
data.scores$Depth = Depth_Species$Depth

data.scores$Primer<-as.factor(data.scores$Primer)
data.scores$Cow<-as.factor(data.scores$Cow)
data.scores$Depth<-as.factor(data.scores$Depth)

head(data.scores)

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes( shape = Primer, colour = Depth))+ 
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "Depth", y = "NMDS2", shape = "Primer used")  
 
xx

#### Now for pooling ####
# now for NMDS plot to visualise it:
#turn abundance data frame into a matrix
m_com = as.matrix(com)
head(m_com)

# now we create our NMDS (set seed makes sure we get the same result every time):
set.seed(123)
nmds = metaMDS(m_com, distance = "bray")
nmds
# for a good representation on our data we are after a stress level of less than 0.2, if its zero then you might have an outlier thats very different to the other samples. 

plot(nmds)

# to plot it in ggplots2 we need to extract the NMDS coordinates for NMDS1 and NMDS2 axes, then put them into a new dataframe called "data.scores"
#extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds)$ sites)

#add columns to data frame 
data.scores$Cow = Depth_Species$Cow
data.scores$Pooling = Depth_Species$Pooling
data.scores$Depth = Depth_Species$Depth

data.scores$Pooling<-as.factor(data.scores$Pooling)
data.scores$Cow<-as.factor(data.scores$Cow)
data.scores$Depth<-as.factor(data.scores$Depth)

data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "1"="Replicate"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "2"="Replicate"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "3"="Replicate"))
count(data.scores, Pooling)

data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "1_2"="Pooled replicates 1 and 2"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "1_2_3"="Pooled replicates 1, 2 and 3"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "1_3"="Pooled replicates 1 and 3"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "2_3"="Pooled replicates 2 and 3"))
count(data.scores, Pooling)

head(data.scores)

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes( shape = Depth, colour = Pooling))+ 
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "Pooling method", y = "NMDS2", shape = "Depth")  
 
xx


#### ASVs ####
Depth_ASVs<-read_excel("/Users/Thomas/Desktop/Nemabiome/nemabiome_new/Nemabiome-refined.xlsx", sheet="Depth_ASVs")
str(Depth_ASVs)
head(Depth_ASVs)

Depth_ASVs$Pooling<-as.factor(Depth_ASVs$Pooling)
Depth_ASVs$Cow<-as.factor(Depth_ASVs$Cow)
Depth_ASVs$Depth<-as.factor(Depth_ASVs$Depth)

com = Depth_ASVs[,5:ncol(Depth_ASVs)]
head(com)

df_com<-as.data.frame(com)

BC<-vegdist(df_com, method="bray")

adonis(BC ~ Depth + Primer + Pooling, Depth_ASVs, perm=200)

#turn abundance data frame into a matrix
m_com = as.matrix(com)
head(m_com)

# now we create our NMDS (set seed makes sure we get the same result every time):
set.seed(123)
nmds = metaMDS(m_com, distance = "bray")
nmds
# for a good representation on our data we are after a stress level of less than 0.2, if its zero then you might have an outlier thats very different to the other samples. 

plot(nmds)

# to plot it in ggplots2 we need to extract the NMDS coordinates for NMDS1 and NMDS2 axes, then put them into a new dataframe called "data.scores"
#extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds)$ sites)

#add columns to data frame 
data.scores$Cow = Depth_ASVs$Cow
data.scores$Primer = Depth_ASVs$Primer
data.scores$Depth = Depth_ASVs$Depth

data.scores$Primer<-as.factor(data.scores$Primer)
data.scores$Cow<-as.factor(data.scores$Cow)
data.scores$Depth<-as.factor(data.scores$Depth)

head(data.scores)

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes( shape = Depth, colour = Primer))+ 
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "Primer", y = "NMDS2", shape = "Depth (%)")  
 
xx

#### Now for pooling ####
adonis(BC ~ Depth + Pooling, Depth_ASVs, perm=200)

# now for NMDS plot to visualise it:
#turn abundance data frame into a matrix
m_com = as.matrix(com)
head(m_com)

# now we create our NMDS (set seed makes sure we get the same result every time):
set.seed(123)
nmds = metaMDS(m_com, distance = "bray")
nmds

plot(nmds)

# to plot it in ggplots2 we need to extract the NMDS coordinates for NMDS1 and NMDS2 axes, then put them into a new dataframe called "data.scores"
#extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds)$ sites)

#add columns to data frame 
data.scores$Cow = Depth_ASVs$Cow
data.scores$Pooling = Depth_ASVs$Pooling
data.scores$Depth = Depth_ASVs$Depth

data.scores$Pooling<-as.factor(data.scores$Pooling)
data.scores$Cow<-as.factor(data.scores$Cow)
data.scores$Depth<-as.factor(data.scores$Depth)

data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "1"="Replicate"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "2"="Replicate"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "3"="Replicate"))
count(data.scores, Pooling)

data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "1_2"="Pooled replicates 1 and 2"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "1_2_3"="Pooled replicates 1, 2 and 3"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "1_3"="Pooled replicates 1 and 3"))
data.scores <- mutate(data.scores, Pooling = recode(.x=Pooling, "2_3"="Pooled replicates 2 and 3"))
count(data.scores, Pooling)

head(data.scores)

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes( shape = Depth, colour = Pooling))+ 
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "Pooling method", y = "NMDS2", shape = "Depth (%)")  
 
xx

### Now for ASV-Primer comparisons at differing levels ###
### ASV 2% ###
Depth_Primer_Comp<-read_excel("/Users/Thomas/Desktop/Nemabiome/nemabiome_new/Nemabiome-refined.xlsx", sheet="Depth(2)_ASVs")
str(Depth_Primer_Comp)
head(Depth_Primer_Comp)

Depth_Primer_Comp$Primer<-as.factor(Depth_Primer_Comp$Primer)
Depth_Primer_Comp$Cow<-as.factor(Depth_Primer_Comp$Cow)
Depth_Primer_Comp$Depth<-as.factor(Depth_Primer_Comp$Depth)

com = Depth_Primer_Comp[,5:ncol(Depth_Primer_Comp)]
head(com)

### skipped PERMANOVA as it requires more than one independent variable! Plus increase the overall error rate!

#turn abundance data frame into a matrix
m_com = as.matrix(com)
head(m_com)

# now we create our NMDS (set seed makes sure we get the same result every time):
set.seed(123)
nmds = metaMDS(m_com, distance = "bray")
nmds

plot(nmds)

# to plot it in ggplots2 we need to extract the NMDS coordinates for NMDS1 and NMDS2 axes, then put them into a new dataframe called "data.scores"
#extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds)$ sites)

#add columns to data frame 
data.scores$Cow = Depth_Primer_Comp$Cow
data.scores$Primer = Depth_Primer_Comp$Primer
data.scores$Depth = Depth_Primer_Comp$Depth

data.scores$Primer<-as.factor(data.scores$Primer)
data.scores$Cow<-as.factor(data.scores$Cow)
data.scores$Depth<-as.factor(data.scores$Depth)

head(data.scores)

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes( shape = Primer, colour = Primer))+ 
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "Primer", y = "NMDS2", shape = "Primer used")  
 
xx

### ASV all%###
Depth_Primer_Comp<-read_excel("/Users/Thomas/Desktop/Nemabiome/nemabiome_new/Nemabiome-refined.xlsx", sheet="Depth(all)_ASVs")
str(Depth_Primer_Comp)
head(Depth_Primer_Comp)

Depth_Primer_Comp$Primer<-as.factor(Depth_Primer_Comp$Primer)
Depth_Primer_Comp$Cow<-as.factor(Depth_Primer_Comp$Cow)
Depth_Primer_Comp$Depth<-as.factor(Depth_Primer_Comp$Depth)

com = Depth_Primer_Comp[,5:ncol(Depth_Primer_Comp)]
head(com)

### skipped PERMANOVA as it requires more than one independent variable! Plus increase the overall error rate!

#turn abundance data frame into a matrix
m_com = as.matrix(com)
head(m_com)

# now we create our NMDS (set seed makes sure we get the same result every time):
set.seed(123)
nmds = metaMDS(m_com, distance = "bray")
nmds

plot(nmds)

# to plot it in ggplots2 we need to extract the NMDS coordinates for NMDS1 and NMDS2 axes, then put them into a new dataframe called "data.scores"
#extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds)$ sites)

#add columns to data frame 
data.scores$Cow = Depth_Primer_Comp$Cow
data.scores$Primer = Depth_Primer_Comp$Primer
data.scores$Depth = Depth_Primer_Comp$Depth

data.scores$Primer<-as.factor(data.scores$Primer)
data.scores$Cow<-as.factor(data.scores$Cow)
data.scores$Depth<-as.factor(data.scores$Depth)

head(data.scores)

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    geom_point(size = 2.5, aes( shape = Primer, colour = Primer))+ 
    theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) + 
    labs(x = "NMDS1", colour = "Primer", y = "NMDS2", shape = "Primer used")  
 
xx

